#!/bin/sh
# addon/lib/dns.sh — DNS hijack (DNAT 53), DoT REJECT (853), DoH blocklist,
# dnsmasq.postconf generator (M3 stub, M5 populates geosite).
#
# Public:
#   dns_hijack_setup                   # create AMNEZIAWG_DNS chain + FORWARD jump
#   dns_hijack_teardown                # remove chain + jumps
#   dns_hijack_add_device <ip>         # add DNAT 53 + REJECT 853 rules for device
#   dns_doh_blocklist_apply <ip>       # apply awg_doh_blocklist CIDRs for device
#   dns_dnsmasq_postconf_generate      # write /jffs/configs/dnsmasq.conf.add
#   dns_dnsmasq_postconf_remove        # delete it

if ! command -v log_info >/dev/null 2>&1; then
    echo "dns.sh: log.sh must be sourced first" >&2
    return 1 2>/dev/null || exit 1
fi

: "${AMNEZIAWG_DNSMASQ_CONF:=/jffs/configs/dnsmasq.conf.add}"

dns_hijack_setup() {
    chain_ensure nat AMNEZIAWG_DNS
    chain_flush nat AMNEZIAWG_DNS
    rule_del_if_exists nat PREROUTING -j AMNEZIAWG_DNS
    iptables -t nat -I PREROUTING -j AMNEZIAWG_DNS
}

dns_hijack_teardown() {
    rule_del_if_exists nat PREROUTING -j AMNEZIAWG_DNS
    chain_delete nat AMNEZIAWG_DNS
}

dns_hijack_add_device() {
    _ip="$1"
    _router="$(nvram get lan_ipaddr 2>/dev/null)"
    if [ -z "${_router}" ]; then
        log_error "dns: nvram lan_ipaddr empty — cannot hijack DNS"
        return 1
    fi
    chain_ensure nat AMNEZIAWG_DNS
    iptables -t nat -A AMNEZIAWG_DNS -s "${_ip}" -p udp --dport 53 \
        -j DNAT --to-destination "${_router}:53"
    iptables -t nat -A AMNEZIAWG_DNS -s "${_ip}" -p tcp --dport 53 \
        -j DNAT --to-destination "${_router}:53"
    rule_add_if_missing filter FORWARD -s "${_ip}" -p tcp --dport 853 \
        -j REJECT --reject-with tcp-reset
    rule_add_if_missing filter FORWARD -s "${_ip}" -p udp --dport 853 \
        -j REJECT
}

dns_doh_blocklist_apply() {
    _ip="$1"
    _list="$(state_get awg_doh_blocklist 2>/dev/null)"
    [ -n "${_list}" ] || return 0
    _IFS_save="${IFS}"; IFS=','
    for _cidr in ${_list}; do
        _cidr="$(printf '%s' "${_cidr}" | tr -d ' ')"
        [ -n "${_cidr}" ] || continue
        rule_add_if_missing filter FORWARD -s "${_ip}" -d "${_cidr}" \
            -p tcp --dport 443 -j REJECT --reject-with tcp-reset
    done
    IFS="${_IFS_save}"
}

dns_dnsmasq_postconf_generate() {
    _tmp="${AMNEZIAWG_DNSMASQ_CONF}.tmp.$$"
    mkdir -p "$(dirname "${AMNEZIAWG_DNSMASQ_CONF}")"
    {
        printf '# Generated by amneziawg — do not edit manually.\n'
        printf '# M3 writes this file empty; M5 will fill geosite ipset directives here.\n'
        printf '# Example (M5):\n'
        printf '#   ipset=/google.com/awg_geo_dst\n'
    } > "${_tmp}"
    mv "${_tmp}" "${AMNEZIAWG_DNSMASQ_CONF}"
}

dns_dnsmasq_postconf_remove() {
    rm -f "${AMNEZIAWG_DNSMASQ_CONF}"
}
