#!/usr/bin/env bats

setup() {
    TMPDIR_TEST="$(mktemp -d)"
    export TMPDIR_TEST
    export AMNEZIAWG_LOG_FILE="${TMPDIR_TEST}/log.out"
    export AMNEZIAWG_CUSTOM_SETTINGS="${TMPDIR_TEST}/cs.txt"
    export AMNEZIAWG_DNSMASQ_CONF="${TMPDIR_TEST}/dnsmasq.conf.add"
    : > "${AMNEZIAWG_CUSTOM_SETTINGS}"

    . "${BATS_TEST_DIRNAME}/fixtures/mock_iptables.sh"
    mock_iptables_install
    export PATH="${TMPDIR_TEST}/bin:${PATH}"

    cat > "${TMPDIR_TEST}/bin/nvram" <<'EOF'
#!/bin/sh
case "$2" in
    lan_ipaddr) echo "192.168.1.1" ;;
    *) echo "" ;;
esac
EOF
    chmod +x "${TMPDIR_TEST}/bin/nvram"

    . "${BATS_TEST_DIRNAME}/../lib/log.sh"
    . "${BATS_TEST_DIRNAME}/../lib/state.sh"
    . "${BATS_TEST_DIRNAME}/../lib/iptables_chain.sh"
    . "${BATS_TEST_DIRNAME}/../lib/dns.sh"
}

teardown() { rm -rf "${TMPDIR_TEST}"; }

@test "dns_hijack_add_device creates DNAT rules for port 53 UDP+TCP" {
    dns_hijack_add_device 192.168.1.100
    iptables -t nat -S AMNEZIAWG_DNS | grep -q -- '-s 192.168.1.100 -p udp --dport 53 -j DNAT --to-destination 192.168.1.1:53'
    iptables -t nat -S AMNEZIAWG_DNS | grep -q -- '-s 192.168.1.100 -p tcp --dport 53 -j DNAT --to-destination 192.168.1.1:53'
}

@test "dns_hijack_add_device applies DoT REJECT for port 853" {
    dns_hijack_add_device 192.168.1.100
    iptables -S FORWARD | grep -q -- '-s 192.168.1.100 -p tcp --dport 853 -j REJECT'
    iptables -S FORWARD | grep -q -- '-s 192.168.1.100 -p udp --dport 853 -j REJECT'
}

@test "dns_doh_blocklist_apply with empty list is noop" {
    state_set "awg_doh_blocklist" ""
    dns_doh_blocklist_apply 192.168.1.100
    ! iptables -S FORWARD | grep -q -- '--dport 443 -j REJECT'
}

@test "dns_doh_blocklist_apply creates REJECT per CIDR" {
    state_set "awg_doh_blocklist" "1.1.1.1/32,8.8.8.8/32"
    dns_doh_blocklist_apply 192.168.1.100
    iptables -S FORWARD | grep -q -- '-s 192.168.1.100 -d 1.1.1.1/32 -p tcp --dport 443 -j REJECT'
    iptables -S FORWARD | grep -q -- '-s 192.168.1.100 -d 8.8.8.8/32 -p tcp --dport 443 -j REJECT'
}

@test "dns_dnsmasq_postconf_generate writes banner with empty body in M3" {
    dns_dnsmasq_postconf_generate
    [ -f "${AMNEZIAWG_DNSMASQ_CONF}" ]
    grep -q 'Generated by amneziawg' "${AMNEZIAWG_DNSMASQ_CONF}"
    grep -q 'M5 will fill' "${AMNEZIAWG_DNSMASQ_CONF}"
}

@test "dns_dnsmasq_postconf_generate is idempotent" {
    dns_dnsmasq_postconf_generate
    _sha1=$(sha1sum "${AMNEZIAWG_DNSMASQ_CONF}" | awk '{print $1}')
    dns_dnsmasq_postconf_generate
    _sha2=$(sha1sum "${AMNEZIAWG_DNSMASQ_CONF}" | awk '{print $1}')
    [ "${_sha1}" = "${_sha2}" ]
}
